# Generated by Django 4.1 on 2022-08-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="id",
            field=models.PositiveIntegerField(
                default=10000, primary_key=True, serialize=False
            ),
        ),
    ]
