# Generated by Django 4.0.7 on 2022-08-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='id',
            field=models.PositiveIntegerField(default=10000, editable=False, primary_key=True, serialize=False),
        ),
    ]
