# Generated by Django 4.0.7 on 2022-09-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accountmodel_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountModel',
            new_name='Account',
        ),
    ]
