# Generated by Django 4.0.7 on 2022-09-18 02:23

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_accountmodel_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='submits',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default=dict, encoder=json.encoder.JSONEncoder),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
