# Generated by Django 4.0.7 on 2022-11-14 11:43

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_score_account_submits_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permissions',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder),
        ),
    ]
