# Generated by Django 4.0.7 on 2022-11-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_submit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
