# Use Google Cloud Platform to manage accounts
google:
  # OAuth Client_Secrets
  client_id: YOUR_GCP_CLIENT_ID
  client_secret: YOUR_GCP_CLIENT_SECRET
  redirect_uri: YOUR_GCP_REDIRECT_URI  # http://127.0.0.1:8000/account/auth

  # pattern to get account id
  email_regex: (.+)@(.+)\\.(.+)  # ^js22-(\d+)@sonline20\.sen\.go\.kr$

url:
  problem_list: https://raw.githubusercontent.com/HURDOO/python-trainer/master/.problems/list.yml
  problem: https://raw.githubusercontent.com/HURDOO/python-trainer/master/.problems/{}/{}.md

# Determines whether DEBUG mode is off
production: false

# user id to hide from ranking
admin_id: -1
