# Use Google Cloud Platform to manage accounts
google:
  # OAuth Client_Secrets
  client_id: YOUR_GCP_CLIENT_ID
  client_secret: YOUR_GCP_CLIENT_SECRET
  redirect_uri: YOUR_GCP_REDIRECT_URI  # http://127.0.0.1:8000/account/auth

  # Regex pattern to get account ID (First group will be used for ID; if group doesn't exist, entire ID from email will be used)
  email_regex: (.+)@(.+)\\.(.+)  # ^js22-(\d+)@sonline20\.sen\.go\.kr$

# Whether to disable developer debug mode. Always set to true in production!
production: false

# user id to hide from ranking
admin_id: -1
