# Generated by Django 4.0.7 on 2022-12-19 06:44

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('manito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manitoaccount',
            name='about_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manitoaccount',
            name='about_text_record',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default=list, encoder=json.encoder.JSONEncoder),
        ),
    ]
