# Generated by Django 4.0.7 on 2022-12-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manito', '0003_manitoaccount_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manitoaccount',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
