# Generated by Django 4.0.7 on 2022-12-20 13:00

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('manito', '0006_manitoaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manitoaccount',
            name='my_balance',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default=dict, encoder=json.encoder.JSONEncoder),
        ),
        migrations.AlterField(
            model_name='manitoaccount',
            name='your_balance',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default=dict, encoder=json.encoder.JSONEncoder),
        ),
    ]
