# Generated by Django 4.1 on 2022-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("T", "Test"), ("G", "Grade")],
                        editable=False,
                        max_length=1,
                    ),
                ),
                ("input_data", models.TextField(editable=False, null=True)),
                ("code", models.TextField(editable=False)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("CP", "Complete"),
                            ("TLE", "Time Limit"),
                            ("MLE", "Memory Limit"),
                            ("OLE", "Output Limit"),
                            ("RTE", "Runtime Error"),
                            ("CE", "Compile Error"),
                            ("PRE", "Prepare"),
                            ("ON", "Ongoing"),
                            ("IE", "Internal Error"),
                        ],
                        default="PRE",
                        max_length=3,
                    ),
                ),
                ("time_usage", models.PositiveIntegerField(null=True)),
                ("memory_usage", models.PositiveIntegerField(null=True)),
                ("submit_time", models.DateTimeField(editable=False)),
                ("code_length", models.PositiveIntegerField(editable=False)),
                ("problem_id", models.PositiveIntegerField(editable=False)),
            ],
        ),
    ]
