# Generated by Django 4.1 on 2022-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submit",
            name="user_id",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
