# Generated by Django 4.1 on 2022-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0002_submit_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submit",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
