# Generated by Django 4.0.7 on 2022-09-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_submit_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='input_data',
            new_name='stdin',
        ),
        migrations.AddField(
            model_name='submit',
            name='stderr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='stdout',
            field=models.TextField(null=True),
        ),
    ]
