# Generated by Django 4.0.7 on 2022-09-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_rename_input_data_submit_stdin_submit_stderr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='last_case_idx',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
