# Generated by Django 4.0.7 on 2022-09-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_alter_submit_result_alter_submit_stderr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='stdin',
            field=models.TextField(editable=False, max_length=1024, null=True),
        ),
    ]
