# Generated by Django 4.0.7 on 2022-09-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_alter_submit_stdin'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
